apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: metadata-basic-auth-lightblue-rest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: metadata-basic-auth-lightblue-rest
    app.kubernetes.io/part-of: lightblue-rest
  name: metadata-basic-auth-lightblue-rest
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: metadata-basic-auth-lightblue-rest
status:
  loadBalancer: {}
